version: '3.1'

services:
  odoo:
    image: odoo:18.0  # Sử dụng Odoo 18
    container_name: odoo
    depends_on:
      - postgres_db
    ports:
      - "8069:8069"
    environment:
      - HOST=postgres_db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    restart: unless-stopped

  postgres_db:
    image: postgres:15  # PostgreSQL 15
    container_name: postgres_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  odoo-data:
  postgres-data:
